
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NO = 3;
  public static final int TOTAL = 4;
  public static final int EOF = 0;
  public static final int POINT = 7;
  public static final int ENTIER = 5;
  public static final int ID = 8;
  public static final int error = 1;
  public static final int VIRG = 6;
  public static final int FACTURE = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FACTURE",
  "NO",
  "TOTAL",
  "ENTIER",
  "VIRG",
  "POINT",
  "ID"
  };
}

