
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CODE = 3;
  public static final int NUM = 7;
  public static final int DEUXPOINTS = 5;
  public static final int PF = 10;
  public static final int DECLARATIONS = 2;
  public static final int FONCTION2 = 12;
  public static final int EOF = 0;
  public static final int FONCTION1 = 11;
  public static final int VAR = 8;
  public static final int EGAL = 4;
  public static final int POINTVIRG = 6;
  public static final int error = 1;
  public static final int PO = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DECLARATIONS",
  "CODE",
  "EGAL",
  "DEUXPOINTS",
  "POINTVIRG",
  "NUM",
  "VAR",
  "PO",
  "PF",
  "FONCTION1",
  "FONCTION2"
  };
}

